# Generated by Django 4.1 on 2024-04-02 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('author', models.CharField(blank=True, max_length=60)),
                ('cover', models.CharField(choices=[('HARD', 'Hardcover'), ('SOFT', 'Softcover')], default='HARD', max_length=60)),
                ('inventory', models.PositiveIntegerField()),
                ('daily_fee', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
